name: SonarCloud Scan

on:
  push:
    branches:
      - main  # Change this to your main branch name
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change this to the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
            -Dsonar.organization: saibhargav2001
            -Dsonar.projectKey=SonarCloudCodeAnalysis
