name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Extract PR details
        id: pr-details
        run: |
          echo "PR_NUMBER=$(echo ${{ github.event.number }})" >> $GITHUB_ENV
          echo "PR_AUTHOR=$(echo ${{ github.event.pull_request.user.login }})" >> $GITHUB_ENV
          echo "PR_APPROVERS=$(echo ${{ github.event.pull_request.requested_reviewers }})" >> $GITHUB_ENV
          echo "PR_MERGER=$(echo ${{ github.event.pull_request.merged_by.login }})" >> $GITHUB_ENV

      - name: Send notification to Discord (STARTED)
        run: node send-discord-notification.js STARTED
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          PR_AUTHOR: ${{ env.PR_AUTHOR }}
          PR_APPROVERS: ${{ env.PR_APPROVERS }}
          PR_MERGER: ${{ env.PR_MERGER }}

      - name: Run Cypress tests
        run: npm run test

      - name: Generate Allure report
        run: npm run report

      - name: Upload Allure history
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Send notification to Discord (SUCCEEDED)
        if: success()
        run: node send-discord-notification.js SUCCEEDED
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          PR_AUTHOR: ${{ env.PR_AUTHOR }}
          PR_APPROVERS: ${{ env.PR_APPROVERS }}
          PR_MERGER: ${{ env.PR_MERGER }}

      - name: Send notification to Discord (FAILED)
        if: failure()
        run: node send-discord-notification.js FAILED
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          PR_AUTHOR: ${{ env.PR_AUTHOR }}
          PR_APPROVERS: ${{ env.PR_APPROVERS }}
          PR_MERGER: ${{ env.PR_MERGER }}
